### ISSUE TITLE
Print data in CSV or some easily parseable format

### ISSUE THREAD

**Issue by ivanperez-keera** [bankscrap/bankscrap#26]
Hi bank-scrap team!

First of all, thanks! I've been looking for something like this for years.

The current library lets people use the CLI application, or to write their own Ruby code that uses the library. However, communication with other tools is, I think, not possible (at the moment).

It would be great to have an option to export the data in some easily parseable format, be it csv, json or (worst case) xml. That way I would be able to 1) automatically gather data from my bank using bankscrap and send it to kmymoney, libreoffice, etc. 2) Build a tool in another language (ie. a Haskell web app, like the one I'm building) and get it to download transactions using your application.

Cheers
Ivan

**Comment by javiercr** [comment]
Hello Ivan,

Exporters (CSV and other formats) are coming soon. There is already a PR with an implementation of a CSV exporter:
https://github.com/bank-scrap/bank_scrap/pull/22

As soon as we get this merged we can move on to XML, JSON or whatever format we need.

**Comment by javiercr** [comment]
Hi @ivanperez-keera, sorry for the long silence. We have now added CSV export with #37. If you would like to have JSON support feel free to create a new PR and we'll merge it.
