### ISSUE TITLE
ING Business account

### ISSUE THREAD

**Issue by bluegod** [bankscrap/bankscrap#34]
Is there any way I can use this to connect to my ING business account? I am able to see the transactions for the regular one, but trying to use the business account number doesn't work. (From the website perspective, it is possible to login to the business account once you logged in into the regular one)

**Comment by javiercr** [comment]
@raulmarcosl is who developed the ING adapter, but he had only access to a personal account. Would you like to contribute writing an adapter for ING business account? We could assist you on how to do it :)

**Comment by bluegod** [comment]
@javiercr My accounts are from ING Spain. I might be able to help if it doesn't take much of my time. I thought it would be as easy as changing the endpoint - I see you use `genoma_login/rest/` for the personal account, and I can see that with the developer tools in Chrome at ING direct website. However, I couldn't see the same thing for business. Just a regular POST, but I'm not 100% sure of this...

**Comment by raulmarcosl** [comment]
Hi @bluegod!

As @javiercr said, I don't have access to a ING business account. If you can log in in your business account after log in in the regular one, probably there are using the same endpoints, and only it's necessary a new endpoint, so it should be easy to add it. I recommend you to use [Charles Proxy](www.charlesproxy.com) to see the request for business account access.

If you need any help, just comment here, I promise to answer promptly :)

**Comment by raulmarcosl** [comment]
I'm closing this because we still don't have access to a ING business account. @bluegod, as I said, if you are willing to develop it I can help you, I'm sure it's pretty similar to our current ING adapter.

**Comment by bluegod** [comment]
@raulmarcosl that's fine. I had a quick look at it but from what I could find out it doesn't look like they use the API as with the personal account. 

They make calls to https://m.ingdirect.es but I couldn't intercept much from the mobile app as they use SSL-pinning.

**Comment by javiercr** [comment]
@bluegod I can assist you on how to bypass the SSL pinning, let me know if you're interested :)

**Comment by bluegod** [comment]
@javiercr thanks, I could get help with that - but I'm not sure I'll find an API endpoint. It looks like they just have a web browser running on the business mobile app.

**Comment by javiercr** [comment]
@bluegod you got a new email with some help :)
