### ISSUE TITLE
Errores con CLI y BBVA

### ISSUE THREAD

**Issue by Tak-MK** [bankscrap/bankscrap#42]
Debian 8 (jessie) stable.
Buenas! Tengo un par de fallos al tratar de usarlo desde comandos.

En la consola uso:
`bankscrap balance BBVA --credentials:user=midni password:mipass`

Y recibo el siguiente error:

> ERROR: "bankscrap balance" was called with arguments ["BBVA", "--credentials:user=midni", "password:mipass"]
> Usage: "bankscrap balance BANK"

He intentado ejecutar directamente:
`bankscrap balance BBVA`
exportando antes las variables BANKSCRAP_BBVA_USER y BANKSCRAP_BBVA_PASSWORD y recibo el siguiente error:

> /var/lib/gems/2.1.0/gems/bankscrap-bbva-1.0.0/lib/bankscrap/bbva/bank.rb:14:in `dup': can't dup NilClass (TypeError)
>         from /var/lib/gems/2.1.0/gems/bankscrap-bbva-1.0.0/lib/bankscrap/bbva/bank.rb:14:in`initialize'
>         from /var/lib/gems/2.1.0/gems/bankscrap-1.0.4/lib/bankscrap/cli.rb:87:in `new'
>         from /var/lib/gems/2.1.0/gems/bankscrap-1.0.4/lib/bankscrap/cli.rb:87:in`initialize_client_for'
>         from /var/lib/gems/2.1.0/gems/bankscrap-1.0.4/lib/bankscrap/cli.rb:30:in `balance'
>         from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
>         from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
>         from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
>         from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
>         from /var/lib/gems/2.1.0/gems/bankscrap-1.0.4/bin/bankscrap:5:in`<top (required)>'
>         from /usr/local/bin/bankscrap:23:in `load'
>         from /usr/local/bin/bankscrap:23:in`<main>'

¿Algo de luz sobre el tema?

¡Muchas gracias!

**Comment by ogarcia** [comment]
Buenas,

He estado haciendo pruebas con esto y puedo decir que la parte del BBVA esta completamente rota. Los endpoints ya no son funcionales y el código tiene bastantes bugs.

Por la fecha en la que se ha puesto el primer comentario y viendo las fechas de los commits, me temo que el proyecto esta un poco muerto.

**Comment by Tak-MK** [comment]
Eso parece.. De todos modos entré en la [API](https://www.bbvaapimarket.com/) privada que montaron, haré mi propio mini-script y ya.

**Comment by zjuanma** [comment]
Se ha roto desde hace un par de semanas. A ver si lo arreglan pronto.

**Comment by javiercr** [comment]
Hola! @raulmarcosl y yo estamos pensando en organizar un Hackathon de Bankscrap en Madrid / remoto para mediados-finales de Noviembre. Lo añadimos a la lista de tareas para ese día. ¿Os animáis a participar?

**Comment by raulmarcosl** [comment]
He estado haciendo pruebas con Charles Proxy para ver si hay nuevos endpoints, o al menos poder ver los errores, y cuando está activado la app falla, así que ahora la app de BBVA usa SSL pinning.
![img_0035](https://cloud.githubusercontent.com/assets/906966/19912814/a96bfc86-a09d-11e6-94a4-087060a699aa.png)

**Comment by ogarcia** [comment]
Yo he intentado meterle caña a la web normal y es, literalmente, un infierno.

**Comment by javiercr** [comment]
@Tak-MK @ogarcia @zjuanma disculpad la tardanza. Por fin hemos podido dedicar algo de tiempo a solucionarlo. He abierto un [PR el el repo de bankscrap-bbva](https://github.com/bankscrap/bankscrap-bbva/pull/2).

Nos ayudaría si pudieses probar el branch antes de mergearlo y publicar la gema en rubygems. Para ello:

```
$ git clone -b feature/bankscrap-v2 https://git@github.com/bankscrap/bankscrap-bbva.git
$ cd bankscrap-bbva
$ rake install
$ bankscrap balance BBVA --credentials=user:TU_DNI password:TU_PASSWORD
```

Muchas gracias!

**Comment by zenitraM** [comment]
Creo que ya lo habéis mergeado 😄 pero lo acabo de probar con mi cuenta y funciona bien.
