### ISSUE TITLE
Implement natwest

### ISSUE THREAD

**Issue by ivanperez-keera** [bankscrap/bankscrap#53]
Hi. I was wondering whether it would be possible to also implement a Natwest UK backend.

Thanks.

**Comment by javiercr** [comment]
@ivanperez-keera it would be definitely possible but we need collaboration from someone who has an account for that bank. If you have one, we can assist you on how to create an adapter :)

**Comment by ivanperez-keera** [comment]
Thanks! I have an account, yes.

**Comment by raulmarcosl** [comment]
Hi @ivanperez-keera.

[We have a generator that builds the basic stuff for a bank adapter](https://github.com/bankscrap/bankscrap#start-a-new-bank-adapter-with-the-generator). Once you have the empty adapter, you need to find the right endpoints using your bank app, and a tool like [Charles Proxy](https://www.charlesproxy.com/).

Let us know if you need any help!

**Comment by ivanperez-keera** [comment]
Thanks.

Seeing what my agenda looks like, this is going to take some time for me. I'm quite busy and haven't done any rails in a while.

However, I am happy contributing a pizza and a couple of beers if anyone else with a natwest account wants to give it a go. For real.
