### ISSUE TITLE
Include a way to make it worth it for developers to continue

### ISSUE THREAD

**Issue by ivanperez-keera** [bankscrap/bankscrap#59]
Hi,

I'd like to ensure that there is a main, open source, reference library that we can use to access our account balance and transactions.

I see that development has not progressed since July 19th, 2018 (almost a year ago). Is this project still maintained? Perhaps everything works and no changes were needed, but I worry that this library would simply "die" because the developers lost interest, need, or the incentive to support this project.

If there is a chance this effort might stop, perhaps a patreon would be needed, or some other way of financing the project. I'd be happy to contribute what I reasonably can, if development continues.

**Comment by raulmarcosl** [comment]
Hi Iván,

Yes, the project is still maintained :) We haven't made any changes in the core library (this one), but the different bank's implementations are working with no problem (I use bankscrap-ing to check my balance and my transactions from time to time). I don't have more supported bank accounts, but we haven't received any issue from other banks.

Indeed, we haven't developed any new functionality or additional banks, but we are open to discuss any ideas, or assist to anyone that would like to contribute :)

**Comment by ivanperez-keera** [comment]
Thanks.

I'll close this issue then :) But feel free to open if you feel tempted to stop developing due to any of the reasons mentioned above.

Although the code seems relatively small and well organized, I normally do not have as much time as I'd like to contribute code myself. I wouldn't want to disclose here which banks I operate with and what products I have, but I'd be happy to have a chat online to see if there's a way to make it work with a couple more banks and for products other than accounts :) Let me know what you think.

**Comment by raulmarcosl** [comment]
Understandable. Feel free to write to me at <my_username> at gmail.com to discuss it :)
